// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILPUBvGtXSrBVomozMoGCfXqfbr8Jr0k',
    appId: '1:520964065320:web:0975e3987606ef54ca8d1d',
    messagingSenderId: '520964065320',
    projectId: 'systeme-de-tri-par-couleur',
    authDomain: 'systeme-de-tri-par-couleur.firebaseapp.com',
    storageBucket: 'systeme-de-tri-par-couleur.firebasestorage.app',
    measurementId: 'G-H49QBHF7XH',
    databaseURL:
        'https://systeme-de-tri-par-couleur-default-rtdb.firebaseio.com/', // Add this line
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9skEHYcSPe9KZUuZwGMptmzhRWq8NIHs',
    appId: '1:520964065320:android:c1871243c3596fa8ca8d1d',
    messagingSenderId: '520964065320',
    projectId: 'systeme-de-tri-par-couleur',
    storageBucket: 'systeme-de-tri-par-couleur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDese4n44TnQ6ut31O0-AVSPlZgqNN1N7E',
    appId: '1:520964065320:ios:afdce79da8f9b1fdca8d1d',
    messagingSenderId: '520964065320',
    projectId: 'systeme-de-tri-par-couleur',
    storageBucket: 'systeme-de-tri-par-couleur.firebasestorage.app',
    iosBundleId: 'com.example.colorproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDese4n44TnQ6ut31O0-AVSPlZgqNN1N7E',
    appId: '1:520964065320:ios:afdce79da8f9b1fdca8d1d',
    messagingSenderId: '520964065320',
    projectId: 'systeme-de-tri-par-couleur',
    storageBucket: 'systeme-de-tri-par-couleur.firebasestorage.app',
    iosBundleId: 'com.example.colorproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDILPUBvGtXSrBVomozMoGCfXqfbr8Jr0k',
    appId: '1:520964065320:web:708b03bc82dca069ca8d1d',
    messagingSenderId: '520964065320',
    projectId: 'systeme-de-tri-par-couleur',
    authDomain: 'systeme-de-tri-par-couleur.firebaseapp.com',
    storageBucket: 'systeme-de-tri-par-couleur.firebasestorage.app',
    measurementId: 'G-B0944WBXNF',
  );
}
